import type { MappedFile } from '@/utils/fileMap'

/** 对齐原型 index.html 的 files mock（节选完整可演示集） */
export const MOCK_MAPPED_FILES: MappedFile[] = [
  {
    id: 'f1',
    projectId: 'rd-xmz',
    module: '合同模块',
    path: 'src/views/contract/List.vue',
    authors: ['demo-user', 'alice', 'bob'],
    lastAt: '2026-09-01 09:48',
    lastAuthor: 'demo-user',
    aiBrief:
      '这个文件是合同列表页，历史上主要围绕「怎么查合同、谁能导出、页面好不好用」在改。最近几次改动集中在：从客户详情跳过来时能正确按客户筛选，以及列表加载和样式体验。',
    docs: [
      {
        id: 'REC-001',
        title: '修复合同列表 customerId 筛选',
        at: '2026-09-01 09:48',
        author: 'demo-user',
        summary: '优先读取路由 query.customerId',
        aiBrief:
          '这次改的是：从客户详情点进合同列表时，页面会读取 URL 里的客户 ID，只显示该客户的合同。以前没带这个参数，列表会显示全部合同，看起来像「筛选失效」。',
        clientComments: [
          {
            id: 'cn1',
            author: '王经理',
            role: 'customer',
            content:
              '这次改动符合预期。请确认从客户详情跳转后，刷新页面筛选条件仍然保留，我们验收时会重点测这一条。',
            at: '2026-09-01 11:05',
          },
          {
            id: 'cn2',
            author: '李主管',
            role: 'customer',
            content:
              '能否在列表上方加一行小字，提示当前正在查看哪个客户的合同？业务员有时候不知道自己有没有筛对。',
            at: '2026-09-01 14:22',
          },
        ],
      },
      {
        id: 'REC-004',
        title: '合同列表分页默认值调整',
        at: '2026-08-22 14:10',
        author: 'alice',
        summary: 'pageSize 改为 20',
        aiBrief: '把合同列表默认每页显示条数从较小值改成 20 条，减少翻页次数，适合合同数量较多的场景。',
        clientComments: [
          {
            id: 'cn3',
            author: '王经理',
            role: 'customer',
            content: '20 条一页可以，但如果能记住用户上次选的分页大小更好。',
            at: '2026-08-23 09:10',
          },
        ],
      },
      {
        id: 'REC-007',
        title: '合同列表导出按钮权限',
        at: '2026-08-10 11:02',
        author: 'bob',
        summary: '仅管理员可见导出',
        aiBrief: '导出按钮只对管理员显示，普通成员看不到，避免误导出或权限外的数据下载。',
      },
      {
        id: 'REC-010',
        title: '合同状态标签样式',
        at: '2026-07-28 16:40',
        author: 'alice',
        summary: '统一 tag 颜色',
        aiBrief: '统一了合同状态小标签的颜色规则，不同状态一眼能区分，界面更整齐。',
      },
      {
        id: 'REC-012',
        title: '合同列表骨架屏',
        at: '2026-07-12 09:15',
        author: 'demo-user',
        summary: '加载态体验',
        aiBrief: '列表加载数据时先显示骨架占位动画，用户不会面对空白页，感知上更快。',
      },
    ],
  },
  {
    id: 'f2',
    projectId: 'rd-xmz',
    module: '合同模块',
    path: 'src/api/contract.ts',
    authors: ['demo-user', 'alice'],
    lastAt: '2026-09-01 09:48',
    lastAuthor: 'demo-user',
    docs: [
      {
        id: 'REC-001',
        title: '修复合同列表 customerId 筛选',
        at: '2026-09-01 09:48',
        author: 'demo-user',
        summary: 'Query 增加 customerId?',
      },
      {
        id: 'REC-004',
        title: '合同列表分页默认值调整',
        at: '2026-08-22 14:10',
        author: 'alice',
        summary: '类型补充 pageSize',
      },
      {
        id: 'REC-008',
        title: '合同导出字段接口',
        at: '2026-08-05 10:20',
        author: 'alice',
        summary: '新增 export-fields',
      },
    ],
  },
  {
    id: 'f3',
    projectId: 'rd-xmz',
    module: '客户模块',
    path: 'src/views/customer/Detail.vue',
    authors: ['alice', 'carol'],
    lastAt: '2026-08-30 16:12',
    lastAuthor: 'alice',
    docs: [
      {
        id: 'REC-002',
        title: '申请人导入模板字段调整',
        at: '2026-08-30 16:12',
        author: 'alice',
        summary: '详情页入口联动',
      },
      {
        id: 'REC-005',
        title: '客户详情 Tab 懒加载',
        at: '2026-08-18 09:40',
        author: 'carol',
        summary: '性能优化',
      },
      {
        id: 'REC-009',
        title: '客户跳转合同携带 ID',
        at: '2026-08-01 15:33',
        author: 'alice',
        summary: '路由参数',
      },
      {
        id: 'REC-011',
        title: '客户基础信息校验',
        at: '2026-07-20 13:08',
        author: 'carol',
        summary: '必填项',
      },
    ],
  },
  {
    id: 'f4',
    projectId: 'rd-xmz',
    module: '客户模块',
    path: 'src/components/customer/ImportDialog.vue',
    authors: ['alice'],
    lastAt: '2026-08-30 16:12',
    lastAuthor: 'alice',
    docs: [
      {
        id: 'REC-002',
        title: '申请人导入模板字段调整',
        at: '2026-08-30 16:12',
        author: 'alice',
        summary: '模板列映射',
      },
      {
        id: 'REC-006',
        title: '导入失败行高亮',
        at: '2026-08-12 18:01',
        author: 'alice',
        summary: '错误反馈',
      },
    ],
  },
  {
    id: 'f5',
    projectId: 'rd-xmz',
    module: '基础设施',
    path: 'src/utils/request.ts',
    authors: ['bob', 'demo-user'],
    lastAt: '2026-08-25 10:00',
    lastAuthor: 'bob',
    docs: [
      {
        id: 'REC-003',
        title: '统一鉴权头注入',
        at: '2026-08-25 10:00',
        author: 'bob',
        summary: 'Authorization',
      },
      {
        id: 'REC-013',
        title: '超时重试策略',
        at: '2026-07-05 19:22',
        author: 'demo-user',
        summary: 'retry=1',
      },
    ],
  },
  {
    id: 'f6',
    projectId: 'rd-xmz',
    module: '合同模块',
    path: 'src/views/contract/Detail.vue',
    authors: ['bob'],
    lastAt: '2026-08-19 20:11',
    lastAuthor: 'bob',
    docs: [
      {
        id: 'REC-014',
        title: '合同详情订单 Tab 重构',
        at: '2026-08-19 20:11',
        author: 'bob',
        summary: '拆分 OrderTab',
      },
    ],
  },
  {
    id: 'f7',
    projectId: 'school-portal',
    module: '认证模块',
    path: 'src/auth/AuthGuard.ts',
    authors: ['bob'],
    lastAt: '2026-08-28 11:03',
    lastAuthor: 'bob',
    docs: [
      {
        id: 'REC-SP-01',
        title: '登录态过期提示',
        at: '2026-08-28 11:03',
        author: 'bob',
        summary: '跳转登录',
      },
      {
        id: 'REC-SP-02',
        title: '角色路由守卫',
        at: '2026-08-15 09:00',
        author: 'bob',
        summary: 'role check',
      },
    ],
  },
]
